### ISSUE TITLE
Suggestions on how to build Light - Please help improve this issue!

### ISSUE THREAD

**Issue by HarvHouHacker** [HarvHouHacker/Light-Web-Browser#13]
Hey, everyone who has decided to join! Since building from Firefox source code is taking longer than usual because of problems I can't seem to work around, please suggest different ways on improving Light!

**Comment by HarvHouHacker** [comment]
@peabee I see that you've made some contributions to Puppy Linux. What all kind of programming experience do you have? If you know any one of the languages required to work on this source code, I can promote you to "write" status.

**Comment by HarvHouHacker** [comment]
We may also want to consider a unique revision numbering system. Just because Light 47 is the current stable version doesn't mean that it isn't the 47th revision.

**Comment by peabee** [comment]
> What all kind of programming experience do you have? If you know any one of the languages required to work on this source code

Limited - mainly shellscript these days..... I have no knowledge of the Mozilla build system - which languages are involved?? I doubt that I can contribute much beyond testing.....
I suspect that @cstkingkey abandoned the project at version 49rc because applying the patches to later Firefox versions became too much work....

**Comment by HarvHouHacker** [comment]
> Limited - mainly shellscript these days..... I have no knowledge of the Mozilla build system - which languages are involved??

Shell scripts are fine; there are a few .sh scripts within the code. The README.md in the `master` branch says a lot of what's required to code Light, but here's some of the languages I've run across:
- Plenty of Python scripts. In fact, the last few revisions are migrating towards a fully Python-based configure.
- Some C++ experience is present, if you can mess with compiler code.
- Firefox uses Mercurial heavily for building. The included `mach` script is what configures and builds the browser.
- As I've said, there are some shell-based scripts, which mainly run when called by other scripts.

> I suspect that @cstkingkey abandoned the project at version 49rc because applying the patches to later Firefox versions became too much work....

Perhaps he just needed more people to work with him! I've sent him an invite.

**Comment by HarvHouHacker** [comment]
Unfortunately, I have no idea which patches to apply first. It's possible that I may have to abandon the patches altogether, as @paulrouget has suggested. I'll keep trying to go further back, but I feel like I'm grasping at straws.

Once I can determine the earliest version of Firefox that the patches can be applied to, I may be able to adjust the patches as I move forward. Fingers crossed...

**Comment by HarvHouHacker** [comment]
@peabee What version of Light do you use? Any problems to report?

**Comment by peabee** [comment]
https://sourceforge.net/projects/lightfirefox/files/48/201607300954_gcc232/
i.e. Linux 32-bit GTK+2 Version 48 - contributes 20.6MB to an iso of 252MB

Generally no problems - doesn't play Youtube videos 100% perefctly - but then you use a "grown-up" browser.....I offer Chromium, Firefox, Palemoon and Seamonkey as additional downloads....used to offer Opera but they've ceased 32-bit - Vivaldi is available in 32-bit and may replace Opera.

**Comment by HarvHouHacker** [comment]
@peabee What I find strange is that Light 48 not offered as the latest stable release, yet I'm running that version release on my 64-bit Ubuntu 16.04 laptop, without a lot of issues to report.

> ...doesn't play Youtube videos 100% perefctly - but then you use a "grown-up" browser...
I hope Light *does* do a bit of "growing up"; it's a nice concept, but has yet to have a consistent release.

> I offer Chromium, Firefox, Palemoon and Seamonkey...
Doesn't Firefox slow down Puppy Linux? While Firefox is powerful, I have yet to see it actually load anything *fast*. I haven't used the other three, but I have used other alternate browsers, such as Midori and GNOME Web (Epiphany), and they load things fast, but not well.

> ...used to offer Opera but they've ceased 32-bit...
Opera leans a lot on proprietary; that's part of your problem there. Proprietary software in general, of whatever it doesn't support, abandons it completely.

> Vivaldi is available in 32-bit and may replace Opera.
Sorry, I've never heard of Vivaldi.

**Comment by HarvHouHacker** [comment]
**Heads up** - Several of the issues that we talked on have been closed, and several of my comments have been modified or removed. This does not mean that they will not be reopened, but I'm trying to clean out the unnecessary things I've included which have more to do with my learning programming than it does with building Light.

Once done, I'll create a fork on my own GitHub profile that I will be working on. This may leave JOY Projects somewhat dead for a while, but please don't avoid joining or contributing! The more, the better.

**Comment by stewie** [comment]
Shifting sands. When I logged in there were 2 separate repositories, now only one... idunno where to post this, so move or delete it as you see fit.

For me, "light/fast" is a byproduct ~~ I'm motivated by the desire to preserve privacy and to maintain  resilience. With that in mind, I outright refuse the premise that a "build mechanism/process" will require callout & retrieval of "blobs" at build time. (even though this approach bears consequences, e.g. no "signed cert.pem").  I would also intend to avoid mach, gradle, and any other proprietary "tools".

From what I've seen, the "Telemetry Service" (along with many other 'service' components) is the most pervasive, entwined, bit of piggyback code. Regardless whether the collected telemetry data is exfiltrated (healthservice), the mechanism bogs the code (analogy:Schrödinger's cat) -- beginning with several seconds of wheel-spinning "instrumentation" at each launch, prior to the app's window chrome even being painted. Maddeningly (sez me) the telemetry components can't be ripped out, wholesale, because they're even entwined with garbage collection. Ideally, the code would provide a "no means NO, dammit!" userpref to disable unnecessary/unwanted continual statskeeping.

**Comment by stewie** [comment]
> What I find strange is that Light 48 not offered as the latest stable release, yet I'm running that version release on my 64-bit Ubuntu 16.04 laptop, without a lot of issues to report.

mozillazine.org forum :: third-party builds
In reply to whining "why not MOAR, moar often, moar every version?" inquiries, xunxun has replied stating his priority for attending the needs of his family/children. We should respect that.

> I hope Light does do a bit of "growing up"; it's a nice concept, but has yet to have a consistent release.

I'm saying: we should not expect, let alone count on, that ever happening.

My intended base would be from here: [https://packages.debian.org/stretch/firefox-esr](url)
and can't guess how the "Debian stable" dependencies align with "Ubuntu 16.04.9.6.3"

[http://security.debian.org/debian-security/pool/updates/main/f/firefox-esr/firefox-esr_52.2.0esr.orig.tar.xz](url)
+
[http://security.debian.org/debian-security/pool/updates/main/f/firefox-esr/firefox-esr_52.2.0esr-1~deb9u1.debian.tar.xz](url)
+
test build via
dpkg-buildpackage
???

**Comment by HarvHouHacker** [comment]
I'm glad you were able to express your thoughts on how Firefox is bloated. Yes, Telemetry is not a needed feature, and will be removed in every Light release. Unfortunately, there isn't a "disable telemetry" option, but fortunately, it appears to not be included in source.

**Comment by HarvHouHacker** [comment]
However, you stated about respecting @xunxun1982's priority for Light. I will do so if he requests it, but I intended Light for everyone.

Also, you said that we shouldn't expect Light to "grow up". I wouldn't say that it will never happen, but it probably won't happen in the near future. Wait a few years first...

I'll take a look at Firefox ESR; it may be helpful in building Light.

**Comment by HarvHouHacker** [comment]
@stewie 

> Wondering why someone tagged this post with a frowny face icon? Maybe the mozillazine post I mentioned was by cstingkey, not xunxun?

Sorry, that "frowny face" wasn't directed at the MozillaZine post. It was more towards your reply immediately after the second quote.

**Comment by HarvHouHacker** [comment]
**Heads up** - You may have noticed that my project notes in this repo are gone. In an attempt to make this less about the self-centered owner and more about collaborating with other people, many of the notes I made have been moved to [my fork](https://github.com/HarvHouHacker/Light-Web-Browser/projects). I'm doing a lot more cleaning up in this repo to try to attract more collaborators.

**Comment by HarvHouHacker** [comment]
@AJgotBeard Have you decided what you might want to work on here? I'm curious as to what you may try to tackle.
